# Generated by Django 5.0.4 on 2024-05-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads'),
        ),
    ]
